# Author: Mansha Batra
# SAP ID: 500083753
# ROLL NO: R214220674
# Batch: 5
# Course: Container Orchestration and Infrastructure Automation
# Program: B.TECH CSE, CC&VT


# syntax=docker/dockerfile:1
FROM python:latest

WORKDIR /app

COPY . .

CMD [ "python", "server/server.py" ]